name: Update AUR Packages

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
  schedule:
    - cron: 0 */8 * * *

jobs:
  update-aur-packages:
    name: Update AUR Packages
    environment: AUR-ssh
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      env:
        SSH_PRIV_KEY: ${{ secrets.SSH_PRIV_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ACTOR: ${{ github.actor }}
        CI: true
    steps:
      - uses: actions/checkout@v4
      - run: bash auto-updater.sh
      - name: Setup tmate session
        if: ${{ !cancelled() && github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 15
