name: Update AUR Packages

on:
  workflow_dispatch:
  schedule:
    - cron: 0 */8 * * *

jobs:
  update-aur-packages:
    name: Update AUR Packages
    environment: AUR-ssh
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      env:
        SSH_PRIV_KEY: ${{ secrets.SSH_PRIV_KEY }}
        ACTOR: ${{ github.actor }}
        CI: true
    steps:
      - uses: actions/checkout@v2
      - run: bash auto-updater.sh
